import { View, Text, StyleSheet, ScrollView, Alert } from "react-native"
import { SafeAreaView } from "react-native-safe-area-context"
import { Ionicons } from "@expo/vector-icons"
import * as Print from "expo-print" // Import Print module
import * as Sharing from "expo-sharing" // Import Sharing module
import { COLORS } from "../../constants/colors"
import CustomButton from "../../components/CustomButton" // Import CustomButton

// Dummy data for demonstration
const dummyDatesheet = [
  { id: "e1", course: "CS101 - Programming Fundamentals", date: "August 10, 2025", time: "09:00 AM", room: "Lab 101" },
  { id: "e2", course: "MA201 - Calculus I", date: "August 12, 2025", time: "02:00 PM", room: "Auditorium A" },
  { id: "e3", course: "PH101 - Applied Physics", date: "August 15, 2025", time: "09:00 AM", room: "Hall B" },
  { id: "e4", course: "EN101 - English Composition", date: "August 18, 2025", time: "11:00 AM", room: "Classroom 203" },
]

const DatesheetScreen = () => {
  // Function to generate HTML content for the datesheet
  const generateDatesheetHtml = () => {
    let htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Examination Datesheet</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          h1 { color: ${COLORS.primary}; text-align: center; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 10px; text-align: left; }
          th { background-color: ${COLORS.primaryLight}; color: white; }
          tr:nth-child(even) { background-color: #f2f2f2; }
          .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <h1>University Examination Datesheet</h1>
        <table>
          <thead>
            <tr>
              <th>Course</th>
              <th>Date</th>
              <th>Time</th>
              <th>Room</th>
            </tr>
          </thead>
          <tbody>
    `
    dummyDatesheet.forEach((exam) => {
      htmlContent += `
        <tr>
          <td>${exam.course}</td>
          <td>${exam.date}</td>
          <td>${exam.time}</td>
          <td>${exam.room}</td>
        </tr>
      `
    })
    htmlContent += `
          </tbody>
        </table>
        <div class="footer">
          <p>Generated by Student Portal App - ${new Date().toLocaleDateString()}</p>
        </div>
      </body>
      </html>
    `
    return htmlContent
  }

  // Function to handle the download/print action
  const handleDownloadDatesheet = async () => {
    try {
      const html = generateDatesheetHtml()
      const { uri } = await Print.printToFileAsync({ html })

      if (uri) {
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(uri, {
            mimeType: "application/pdf",
            dialogTitle: "Download Datesheet",
            UTI: "com.adobe.pdf",
          })
        } else {
          Alert.alert("Sharing Not Available", "Sharing is not available on your device.")
        }
      }
    } catch (error) {
      console.error("Error downloading datesheet:", error)
      Alert.alert("Download Failed", "Could not generate or share the datesheet. Please try again.")
    }
  }

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <Text style={styles.headerTitle}>Examination Datesheet</Text>

        {dummyDatesheet.length > 0 ? (
          dummyDatesheet.map((exam) => (
            <View key={exam.id} style={styles.examCard}>
              <View style={styles.examCardHeader}>
                <Ionicons name="calendar-outline" size={24} color={COLORS.primary} />
                <Text style={styles.examCourse}>{exam.course}</Text>
              </View>
              <View style={styles.examDetailRow}>
                <Ionicons name="time-outline" size={18} color={COLORS.textSecondary} />
                <Text style={styles.examDetailText}>
                  {exam.date} at {exam.time}
                </Text>
              </View>
              <View style={styles.examDetailRow}>
                <Ionicons name="location-outline" size={18} color={COLORS.textSecondary} />
                <Text style={styles.examDetailText}>Room: {exam.room}</Text>
              </View>
            </View>
          ))
        ) : (
          <View style={styles.emptyStateCard}>
            <Ionicons name="information-circle-outline" size={30} color={COLORS.info} />
            <Text style={styles.emptyStateText}>No upcoming exams in your datesheet.</Text>
          </View>
        )}

        {/* Download Button */}
        <CustomButton
          title="Download Datesheet (PDF)"
          onPress={handleDownloadDatesheet}
          variant="primary"
          size="large"
          style={styles.downloadButton}
        />
      </ScrollView>
    </SafeAreaView>
  )
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContent: {
    padding: 24,
    paddingBottom: 80, // Add extra padding for bottom tab bar
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: COLORS.textPrimary,
    marginBottom: 20,
    textAlign: "center",
  },
  examCard: {
    backgroundColor: COLORS.surface, // Use new surface color
    borderRadius: 15,
    padding: 20,
    marginBottom: 15,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 4,
  },
  examCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLight,
    paddingBottom: 10,
  },
  examCourse: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginLeft: 10,
    flexShrink: 1,
  },
  examDetailRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 8,
    marginLeft: 5, // Indent details slightly
  },
  examDetailText: {
    fontSize: 15,
    color: COLORS.textSecondary,
    marginLeft: 10,
  },
  emptyStateCard: {
    backgroundColor: COLORS.surface, // Use new surface color
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    alignItems: "center",
    justifyContent: "center",
    minHeight: 100,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 4,
  },
  emptyStateText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginTop: 10,
    textAlign: "center",
  },
  downloadButton: {
    marginTop: 30,
    marginBottom: 20,
  },
})

export default DatesheetScreen
